### ISSUE TITLE
用两个n来转换ん会不会更好一点？

### ISSUE THREAD

**Issue by mannfuri** [xrq-phys/rime-hifumi#4]
想输入日文的“转移”。
现在这个mozc词库，要输入teni。
![image](https://github.com/xrq-phys/rime-hifumi/assets/91338215/1c94b197-dd2f-4fae-be41-af25682fcb03)

**Comment by xrq-phys** [comment]
嗯 是的

当时在转表的时候主要在思考的是 其他日语输入法在 `n` 后跟随非 あ 行假名的时候会转换成 `ん○` 这件事 所以就没有用 `nn` 来转换。严格来说确实应该用 `nn` 的。

可能这边更好的方法是用 `nn` 来转换 ん 然后在 schema 里面把 `[^n]n[^aiueo]` 转换成 `$1nn$2`

我来测试一下

**Comment by mannfuri** [comment]
OK多谢
那我就坐等成品了 :D

**Comment by xrq-phys** [comment]
Done: cebcfe38cc87

**Comment by xrq-phys** [comment]
多谢 issue. 我先把这个 close 了. 如果有需要请重新打开
